### ISSUE TITLE
AddPdfFileName

### ISSUE THREAD

**Issue by cerdts** [uppercuut/TemplateToPdf.Demo#2] opened 2022-04-05 21:54 UTC
The generated PDF filename is always "ById.pdf" regardless of what is contained in the .AddPdfFileName("Filename") method. This can be observed in the Demo based on the TheStarterKit.

**Comment by cerdts** [comment] 2022-04-07 15:57
Name:
  wkhtmltopdf 0.12.6 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

**Comment by IbrahimMNada** [comment] 2022-04-08 20:50
Hello there , 

the issue is fixed now. 

Install-Package Our.Umbraco.TemplateToPdf -Version 1.0.10

**Closed as completed by IbrahimMNada** 2022-04-08 20:51 UTC

**Comment by cerdts** [comment] 2022-04-08 20:53
Thank you
